version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:8001"

  backend:
    build: ./backend
    ports:
      - "8080:8002"

  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=casino
    volumes:
      - ./volume/db:/var/lib/postgresql/data/